-- Create MyGo supplier tables
create table if not exists public.mygo_cities (
  id bigint generated by default as identity primary key,
  mygo_id text not null,
  name text not null,
  country text,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists mygo_cities_mygo_id_idx on public.mygo_cities (mygo_id);
create index if not exists mygo_cities_name_idx on public.mygo_cities (name);

create table if not exists public.mygo_hotels (
  id bigint generated by default as identity primary key,
  mygo_id text not null,
  city_mygo_id text,
  name text,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists mygo_hotels_mygo_id_idx on public.mygo_hotels (mygo_id);
create index if not exists mygo_hotels_city_mygo_id_idx on public.mygo_hotels (city_mygo_id);

create table if not exists public.suppliers_config (
  id bigint generated by default as identity primary key,
  supplier text not null unique,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.mygo_cities enable row level security;
alter table public.mygo_hotels enable row level security;
alter table public.suppliers_config enable row level security;

create policy "mygo_cities_select_anon" on public.mygo_cities
for select to anon using (true);

create policy "mygo_cities_select_authenticated" on public.mygo_cities
for select to authenticated using (true);

create policy "mygo_hotels_select_anon" on public.mygo_hotels
for select to anon using (true);

create policy "mygo_hotels_select_authenticated" on public.mygo_hotels
for select to authenticated using (true);
