create table if not exists public.mygo_cities (
  id text primary key,
  name text not null
);

create index if not exists mygo_cities_name_idx on public.mygo_cities (name);

create table if not exists public.mygo_hotels (
  id text primary key,
  name text not null,
  city_id text not null references public.mygo_cities (id) on delete cascade
);

create table if not exists public.suppliers_config (
  id bigint generated by default as identity primary key,
  supplier text not null unique,
  config jsonb not null default '{}'::jsonb
);
